version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: travel-platform-db
    environment:
      POSTGRES_USER: travel
      POSTGRES_PASSWORD: travel_dev_pass
      POSTGRES_DB: travel_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../../infra/sql/seeds:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U travel"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
